const STORAGE_KEY='travel2.profile.v2';
const DESTINATIONS=[['ukraine','Україна'],['europe','Європа'],['sea','Море'],['cruise','Круїз'],['mountains','Гори'],['anywhere','Будь-куди'],['worldwide','Worldwide']];
const PREFS={quiet:'Тиша',spa:'SPA',pools:'Басейни',nature:'Природа',active:'Активність',kids:'Дітям',culture:'Екскурсії',entertainment:'Двіж'};
let defaultProfile,hotels=[];

const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function loadProfile(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved&&saved.version>=2?saved:structuredClone(defaultProfile)}catch{return structuredClone(defaultProfile)}}
function saveProfile(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function groupType(p){return p.travellers.some(t=>Number(t.age)<18)?'family':'couple'}
function nights(p){if(p.date.mode!=='exact')return null;const a=new Date(p.date.checkIn+'T00:00:00Z'),b=new Date(p.date.checkOut+'T00:00:00Z');const n=Math.round((b-a)/86400000);return n>0?n:null}
function normalizedText(h,v){return [h.name,h.location,h.region,h.group,v?.verdict,...(v?.pros||[]),...(v?.cons||[])].join(' ').toLowerCase()}
function preferenceFit(h,v,p){const text=normalizedText(h,v);const signals={quiet:['тихо','тиша','камерн','ліс','природ'],spa:['spa','спа','саун','хамам','парн'],pools:['басейн','аква','терм'],nature:['ліс','гора','природ','річк','парк'],active:['актив','спорт','велосип','похід'],kids:['дитяч','kids','аніма','педагог'],culture:['екскурс','музей','замок','культур'],entertainment:['аніма','розваг','програм','бар','вечір']};let weighted=0,total=0;for(const [k,wRaw] of Object.entries(p.preferences||{})){const w=Number(wRaw)||0;if(!w)continue;total+=w;const hit=(signals[k]||[]).some(x=>text.includes(x));weighted+=w*(hit?1:0.35)}return total?weighted/total:0.5}
function adaptHotel(raw,p){const variantKey=groupType(p),v=raw[variantKey];if(!v?.eligible)return null;const regular=Number(v.pricePerNight)||null;const snap={hotelId:raw.id,profileKind:variantKey,availability:v.priceStatus==='unknown'?'needs_confirmation':'candidate',pricePerNight:regular,totalPrice:Number(v.total7Nights)||null,room:null,inclusions:v.included||'',meals:v.meals||'',cancellation:'needs_confirmation',childSupplement:variantKey==='family'?'embedded_or_needs_confirmation':null,bestOfferPerNight:regular,checkedAt:raw.checkedAt||null,source:raw.url||null};const hotel={id:raw.id,name:raw.name,location:raw.location,region:raw.region,group:raw.group,url:raw.url,indoorSpa:!!raw.indoorSpa,thermal:!!raw.thermal};const base=Number(v.score)||0;const budget=Number(p.budgetPerNight)||0;const budgetFit=!regular||!budget?0.5:regular<=budget?1:clamp(1-(regular-budget)/budget,0,1);const pref=preferenceFit(raw,v,p);const profileScore=clamp(base*0.65+budgetFit*2+pref*1.5,0,10);return {hotel,snapshot:snap,variant:v,profileScore,budgetFit,pref}}
function destinationAllowed(x,p){const g=(x.hotel.group||'').toLowerCase(),r=(x.hotel.region||'').toLowerCase();switch(p.destinationMode){case'mountains':return g.includes('карпат')||r.includes('карпат');case'ukraine':return true;case'anywhere':case'worldwide':return true;case'europe':case'sea':case'cruise':return false;default:return true}}
function renderControls(p){const root=document.getElementById('profileControls');root.innerHTML=`<h3>Куди?</h3><div class="chips" id="destinations">${DESTINATIONS.map(([v,l])=>`<button class="chip ${p.destinationMode===v?'active':''}" data-dest="${v}">${l}</button>`).join('')}</div><h3>Коли?</h3><div class="chips">${['exact','flexible','season','schoolHoliday'].map(v=>`<button class="chip ${p.date.mode===v?'active':''}" data-date-mode="${v}">${({exact:'Точні дати',flexible:'Гнучко',season:'Пора року',schoolHoliday:'Канікули'})[v]}</button>`).join('')}</div><div id="dateFields"></div><h3>Хто їде?</h3><div id="travellers"></div><button id="addTraveller">+ Додати людину</button><h3>Бюджет / ніч</h3><input id="budget" type="number" min="1000" step="500" value="${Number(p.budgetPerNight)||7000}"><h3>Що важливо?</h3><div id="preferences">${Object.entries(PREFS).map(([k,l])=>`<label class="slider"><span>${l}</span><input type="range" min="0" max="5" value="${Number(p.preferences?.[k])||0}" data-pref="${k}"><b>${Number(p.preferences?.[k])||0}</b></label>`).join('')}</div>`;renderDateFields(p);renderTravellers(p);bindControls(p)}
function renderDateFields(p){const d=document.getElementById('dateFields');if(!d)return;if(p.date.mode==='exact')d.innerHTML=`<label>Заїзд <input type="date" id="checkIn" value="${p.date.checkIn}"></label> <label>Виїзд <input type="date" id="checkOut" value="${p.date.checkOut}"></label>`;else if(p.date.mode==='flexible')d.innerHTML=`<label>Від <input type="date" id="flexFrom" value="${p.date.flexFrom}"></label> <label>До <input type="date" id="flexTo" value="${p.date.flexTo}"></label>`;else if(p.date.mode==='season')d.innerHTML=`<select id="season"><option value="winter">Зима</option><option value="spring">Весна</option><option value="summer">Літо</option><option value="autumn">Осінь</option></select>`;else d.innerHTML=`<select id="schoolHoliday"><option value="autumn">Осінні</option><option value="winter">Зимові</option><option value="spring">Весняні</option><option value="summer">Літні</option></select>`;const s=d.querySelector('select');if(s)s.value=p.date[p.date.mode==='season'?'season':'schoolHoliday']||s.value}
function renderTravellers(p){document.getElementById('travellers').innerHTML=p.travellers.map((t,i)=>`<div class="traveller"><input value="${esc(t.label)}" data-label="${i}" aria-label="Ім'я мандрівника"><input type="number" min="0" max="120" value="${Number(t.age)||0}" data-age="${i}" aria-label="Вік"><button data-remove="${i}" ${p.travellers.length<=1?'disabled':''}>×</button></div>`).join('')}
function bindControls(p){const changed=()=>{saveProfile(p);renderAll(p)};document.querySelectorAll('[data-dest]').forEach(b=>b.onclick=()=>{p.destinationMode=b.dataset.dest;p.rankingMode=['sea','worldwide'].includes(p.destinationMode)?p.destinationMode:'ukraine';renderControls(p);changed()});document.querySelectorAll('[data-date-mode]').forEach(b=>b.onclick=()=>{p.date.mode=b.dataset.dateMode;renderControls(p);changed()});document.getElementById('dateFields').onchange=e=>{if(e.target.id)p.date[e.target.id]=e.target.value;changed()};document.getElementById('budget').onchange=e=>{p.budgetPerNight=Number(e.target.value)||0;changed()};document.querySelectorAll('[data-pref]').forEach(s=>s.oninput=e=>{p.preferences[e.target.dataset.pref]=Number(e.target.value);e.target.nextElementSibling.textContent=e.target.value;saveProfile(p);renderAll(p)});document.getElementById('travellers').onchange=e=>{if(e.target.dataset.label!==undefined)p.travellers[+e.target.dataset.label].label=e.target.value;if(e.target.dataset.age!==undefined)p.travellers[+e.target.dataset.age].age=clamp(Number(e.target.value)||0,0,120);changed()};document.getElementById('travellers').onclick=e=>{if(e.target.dataset.remove!==undefined&&p.travellers.length>1){p.travellers.splice(+e.target.dataset.remove,1);renderControls(p);changed()}};document.getElementById('addTraveller').onclick=()=>{if(p.travellers.length<5){p.travellers.push({label:`Мандрівник ${p.travellers.length+1}`,age:18});renderControls(p);changed()}}}
function renderAll(p){const n=nights(p);document.getElementById('profileSummary').innerHTML=`<b>${p.travellers.length} ос.</b> · ${groupType(p)==='family'?'сімейний':'для двох/дорослих'} профіль · бюджет ${Number(p.budgetPerNight).toLocaleString('uk-UA')} грн/ніч${n?` · ${n} ночей`:''}`;const adapted=hotels.map(h=>adaptHotel(h,p)).filter(Boolean).filter(x=>destinationAllowed(x,p)).sort((a,b)=>b.profileScore-a.profileScore);document.getElementById('status').textContent=`Підібрано ${adapted.length} кандидатів із production hotel base. Ranking перераховано під поточний профіль.`;document.getElementById('results').innerHTML=adapted.slice(0,12).map(x=>`<article class="card"><div class="cardtop"><div><h3>${esc(x.hotel.name)}</h3><div class="meta">${esc(x.hotel.location)} · ${esc(x.hotel.group)}</div></div><div class="score">${x.profileScore.toFixed(1)}<small>/10</small></div></div><div class="price">${x.snapshot.pricePerNight?x.snapshot.pricePerNight.toLocaleString('uk-UA')+' грн / ніч':'Ціна уточнюється'}</div><p>${esc(x.variant.verdict||'')}</p><div class="hint">Base score ${Number(x.variant.score||0).toFixed(1)} · budget fit ${Math.round(x.budgetFit*100)}% · preference fit ${Math.round(x.pref*100)}% · ${esc(x.snapshot.availability)}</div></article>`).join('')||'<p>Для цього режиму поки немає підключених кандидатів.</p>'}

Promise.all([fetch('profile.json',{cache:'no-store'}),fetch('../hotels.json',{cache:'no-store'})]).then(async([pr,hr])=>{defaultProfile=await pr.json();defaultProfile.version=2;defaultProfile.preferences={quiet:5,spa:5,pools:4,nature:5,active:2,kids:0,culture:2,entertainment:1,...defaultProfile.preferences};hotels=(await hr.json()).hotels||[];const p=loadProfile();document.body.dataset.travel2='ready';renderControls(p);renderAll(p)}).catch(err=>{const s=document.getElementById('status');if(s)s.textContent='Помилка завантаження: '+err.message;console.error(err)});