import fs from 'node:fs';
const jsonFiles=fs.readdirSync('.').filter(f=>/^hotels.*\.json$/.test(f));
let hotels=[];
for(const file of jsonFiles){const j=JSON.parse(fs.readFileSync(file,'utf8'));for(const h of j.hotels||[])hotels.push({...h,__file:file})}
const aliases=[['solva-resort-medical-spa','solva'],['chervona-ruta-shayan','chervona-ruta'],['taor-karpaty','taor'],['vedmezha-gora-yaremche','vedmezha-gora']];
const ids=new Map();for(const h of hotels){const a=ids.get(h.id)||[];a.push(h.__file);ids.set(h.id,a)}
let bad=false;
for(const [canonical,legacy] of aliases){if(ids.has(canonical)&&ids.has(legacy))console.log('SOURCE_ALIAS_PAIR',canonical,legacy)}
for(const [id,files] of ids){if(files.length>1)console.log('MULTI_SOURCE_ID',id,files.join(','))}
for(const file of ['app.js','app-entry.js','app-20260914.js','pearls-bootstrap.js','goral-bootstrap.js','vedmezha-bootstrap.js','fb-spa-bootstrap.js','romantik-bootstrap.js','mirotel-bootstrap.js']){if(!fs.existsSync(file)){console.error('MISSING_RUNTIME_FILE',file);bad=true}}
const runtimeSources=['hotels.json','hotels-20260914.json','hotels-pearls-20260914.json','hotels-lowprice-20260916.json','hotels-discovery-20260916.json','hotels-discovery-20260916-1145.json','hotels-discovery-20260916-1542.json','hotels-discovery-20260916-1940.json','hotels-discovery-20260916-2039.json','hotels-discovery-20260916-2138.json','hotels-discovery-20260916-2237.json','hotels-helikon-20260917.json','hotels-discovery-20260920-tavel.json','hotels-discovery-20260920-goral.json','hotels-discovery-20260920-vedmezha-gora.json','hotels-discovery-20260920-fb-spa.json','hotels-discovery-20260920-romantik-spa.json','hotels-discovery-20260919-mirotel.json','hotels-discovery-20260920-taor.json'];const merged=new Map();for(const file of runtimeSources){const j=JSON.parse(fs.readFileSync(file,'utf8'));for(const h of j.hotels||[])merged.set(h.id,h)}for(const [canonical,legacy] of aliases){if(merged.has(canonical))merged.delete(legacy)}console.log('RUNTIME_UNIQUE_PHYSICAL_COUNT',merged.size);
const runtimeIds=[...merged.keys()].sort();
console.log('RUNTIME_CANONICAL_IDS',JSON.stringify(runtimeIds));
const runtimeAliasFamilies=[['solva-resort-medical-spa','solva'],['chervona-ruta-shayan','chervona-ruta'],['taor-karpaty','taor'],['vedmezha-gora-yaremche','vedmezha-gora']];const aliasLeak=runtimeAliasFamilies.flatMap(([canonical,legacy])=>merged.has(canonical)&&merged.has(legacy)?[[canonical,legacy]]:[]);
if(aliasLeak.length){console.error('RUNTIME_ALIAS_LEAK',JSON.stringify(aliasLeak));bad=true}else console.log('RUNTIME_ALIAS_LEAK_COUNT',0);
const scenarioChipCount=(h,v)=>{if(!v||v.eligible===false)return null;const a=[];const add=x=>{if(a.length<8&&!a.includes(x))a.push(x)};const b=[...(v.pros||[]),v.included||'',v.verdict||'',h.description||'',v.meals||''].join(' ').toLowerCase();if(h.thermal||/термал/.test(b))add('thermal');if(/солян/.test(b))add('salt');if(/хамам|турецьк.*парн/.test(b))add('hammam');if(/трираз|3-раз|повне харч/.test(b))add('3meal');else if(/сніданок.*вечер|снідан.*\\+.*вечер|двораз|2-раз/.test(b))add('hb');else if(/снідан/.test(b))add('bb');if(/масаж/.test(b))add('massage');if(/поїздк|екскурс/.test(b))add('trip');if(/велика.*територ|закрита територ|великий парк|територія.*прогуля/.test(b))add('territory');if(/серед ліс|у ліс|лісов|природн.*локац|тиха локац|тихо/.test(b))add('nature');if(/дитяч.*басейн/.test(b))add('kidpool');if(/аніма|kids club|дитяч.*кімнат/.test(b))add('kids');if(/джакуз/.test(b))add('jacuzzi');if(/крит.*басейн/.test(b))add('pool');if(/саун|парна/.test(b))add('sauna');if(/бювет|мінеральн.*вод/.test(b))add('water');if(/спортзал|тренажер/.test(b))add('gym');const w=h.features||h.wellness||{};if(w.pool===true||w.indoorPool===true)add('pool');if(h.indoorSpa===true&&w.pool!==true&&w.indoorPool!==true&&!/крит.*басейн/.test(b))add('indoor-spa');if(w.hammam===true)add('hammam');if(w.jacuzzi===true)add('jacuzzi');if(w.sauna===true)add('sauna');if(w.gym===true)add('gym');if(w.childPool===true)add('kidpool');if(w.thermalPools===true)add('thermal');if(w.steamRooms===true)add('steam');if(w.kidsRoom===true||w.animation===true)add('kids');if(/римськ.*парн|паров.*лазн|steam/.test(b))add('steam');if(/kids club|арт-клуб|дитяч.*клуб|майстер-клас|міні-кінотеатр|кінотеатр/.test(b))add('kids');if(/старе міст|музе|ботанічн.*сад|парк.*поруч|піша доступ|майстер-клас/.test(b))add('nearby');if(/ресторан/.test(b))add('restaurant');if(/spa у комплекс|spa-центр|spa вход|spa включ|критий spa|повноцінн.*spa/.test(b))add('spa');if(/простір для прогуля|простора територ|велика територ/.test(b))add('territory');if(/аквапарк/.test(b))add('aquapark');if(/дитяч.*майданчик|дитяче меню/.test(b))add('kids');if(/парк історії землі|замок любарта|центр міста|центр хмельницького|тернопіль дає|кам’янець-подільський|чернівц|старе міст/.test(b))add('nearby');if(/басейн.*гідромасаж|гідромасаж.*басейн/.test(b))add('hydro');if(/сніданок і spa включ|spa у тарифі|spa входять|spa входить|spa включен|spa-access|spa access/.test(b))add('spa-included');if(/сімейні номери|family room|категорії 2\+1|тримісний стандарт|додаткове місце/.test(b))add('2+1');if(/косино|берегове|винний напрям|15 км до ужгорода|близькість до ужгорода/.test(b))add('nearby');if(/тренажерн.*зал|спортзал/.test(b))add('gym');return a.length};
const chipUnderfill=[];for(const h of merged.values())for(const s of ['couple','family']){const n=scenarioChipCount(h,h[s]);if(n!==null&&n<4)chipUnderfill.push({id:h.id,scenario:s,count:n})}console.log('CHIP_UNDERFILL_COUNT',chipUnderfill.length);if(chipUnderfill.length)console.log('CHIP_UNDERFILL',JSON.stringify(chipUnderfill));const requiredLiveIds=['taor-karpaty','goral-hotel-spa','vedmezha-gora-yaremche','fb-spa-resort','romantik-spa-yaremche','mirotel-truskavets'];for(const id of requiredLiveIds){const h=merged.get(id);if(!h){console.error('STRANDED_RUNTIME_CARD',id);bad=true;continue}if(!h.couple||!h.family||typeof h.couple.eligible!=='boolean'||typeof h.family.eligible!=='boolean'){console.error('UNRENDERABLE_RUNTIME_CARD',id);bad=true}}if(bad)process.exit(1);console.log('PREDEPLOY_OK',jsonFiles.length,'hotel JSON files checked');
